### PR TITLE
refactor!: rework/simplify implementation of SSL keystore hot-reload

### PR DESCRIPTION
**Pull request by jimpil**
It turns out that jetty already has support for this in the `KeystoreScanner` class!

### CODE REVIEW

**Comment by sunng87** [comment]
Never mind I was just asking for alternative solutions. During the 0.x period we are open to breaking changes especially for minor new change like this.

**Comment by jimpil** [comment]
Just a quick question -  I was wondering whether you plan to release this any time soon (e.g. this week), or not...

**Comment by sunng87** [comment]
Yes. I'm going to create a release today or tomorrow.

**Comment by sunng87** [comment]
0.21 has been released to clojars

**Pull request merged**
