### PR TITLE
feat: add option  to enable virtual threads support for thread pool

### PR DESCRIPTION
**Pull request by sunng87**
Add a dedicated option to enable virtual threads support for thread pool created by our adapter.

### CODE REVIEW

**Comment by jasonjckn** [comment]
What happens if they use an older version of JDK without any class org.eclipse.jetty.util VirtualThreads on the classpath? The bytecode may not load I think (?) genuinely trying to remember .

**Comment by sunng87** [comment]
Unexpected error (UnsupportedClassVersionError) macroexpanding 
clojure.core/gen-class at (ring/adapter/jetty9/handlers/sync.clj:1:1).
org/eclipse/jetty/server/Handler$Abstract has been compiled by a more 
recent version of the Java Runtime (class file version 61.0), this 
version of the Java Runtime only recognizes class file versions up to 55.0

Jetty 12 has a minimal Java version requirement so we should not hit 
virtual thread api issue.

**Comment by sunng87** [comment]
Our CI can ensure it compiles and works on 17

**Comment by sunng87** [comment]
Actually this `VirtualThreads` class in Jetty is a feature prober to detect if platform has virtual threads support. It uses reflection to get actually JDK virtual thread executor.

**Comment by darkleaf** [comment]
What is the correct `max-threads` size to use when dealing with virtual threads?
Should it be Integer/MAX_VALUE?

**Comment by jasonjckn** [comment]
> What is the correct `max-threads` size to use when dealing with virtual threads? Should it be Integer/MAX_VALUE?

50-200 is usually a good number, these are platform threads not virtual threads,  platform threads are used for NIO select/accept/destroy. When dispatching an action from AdaptiveExecutionStrategy which calls into user code, a virtual thread is used, of which there's no out-of-the-box way to set a 'max' / bound. There's a bit more information about it from https://webtide.com/jetty-12-virtual-threads-support/.

**Comment by sunng87** [comment]
Yes, typically it's your cores multiplies 1 or 2. It depends on your workload.

**Pull request merged**
