### PR TITLE
use `gen-class` for proxying handlers

### PR DESCRIPTION
**Pull request by jimpil**
For #92

### CODE REVIEW

**Comment by jimpil** [comment]
Tests pass but I noticed that the websocket test (at the end of the test file) is commented out. Do you have a way of testing that websockets work as expected?

**Comment by jimpil** [comment]
I have working code (locally) that completely retires the `servlet/make-output-stream` (which also returns a `proxy`). Basically, the only reason for that proxy is the `(.complete context)`  expression inside the `close` override. The `write` overrides are there purely as an optimisation to `FilterOutputStream`.  So, realising that, we can do the following instead:
```clj
(->> (.getOutputStream response) 
     (protocols/write-body-to-stream body response-map))
(some-> context .complete)
```
Do you have any objections including this here?

**Comment by sunng87** [comment]
@jimpil that sounds good to me please go ahead

**Comment by jimpil** [comment]
@sunng87 The PR is now ready. I want to draw your attention once again to the implications of `gen-class` wrt to AOT - i.e. most of the project is now AOT-ed.  

By the way, do you happen to have any load/performance testing that you do for PRs like this? If not, [this](https://github.com/jetty-project/jetty-load-generator) looks rather promising.

**Review by sunng87 — APPROVED** [review]

**Comment by jimpil** [comment]
Right, so basically 43% better latency, with about 10x less variance...Not too shabby! ;)

**Pull request merged**
